theme: jekyll-theme-modernist

# Site Settings
locale                    : "fa-IR"
title                     : "Python Course"
name                      : "سعید محققی Saeed Mohagheghi"

description               : "دوره آموزش پایتون"
show_downloads            : true
